import Navbar from "../Navbar";
import Footer from "../Footer";
import Head from "next/head";

const Main = ({ children }) => {
  return (
    <div>
      <Head>
        <title>Amaar&#39;s Homepage</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon-16x16.png" />
      </Head>
      <main className="h-screen mx-auto">
        <Navbar />
        {children}
        <Footer />
      </main>
    </div>
  );
};

export default Main;
